/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as LivrosLivroIdRouteImport } from './routes/livros/$livroId'
import { Route as LivrosBuscarRouteImport } from './routes/livros/buscar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const LivrosLivroIdRoute = LivrosLivroIdRouteImport.update({
  id: '/livros/$livroId',
  path: '/livros/$livroId',
  getParentRoute: () => rootRouteImport,
} as any)
const LivrosBuscarRoute = LivrosBuscarRouteImport.update({
  id: '/livros/buscar',
  path: '/livros/buscar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/livros/$livroId': typeof LivrosLivroIdRoute
  '/livros/buscar': typeof LivrosBuscarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/livros/$livroId': typeof LivrosLivroIdRoute
  '/livros/buscar': typeof LivrosBuscarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/livros/$livroId': typeof LivrosLivroIdRoute
  '/livros/buscar': typeof LivrosBuscarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/home' | '/login' | '/perfil' | '/livros/$livroId' | '/livros/buscar'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/home' | '/login' | '/perfil' | '/livros/$livroId' | '/livros/buscar'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/login'
    | '/perfil'
    | '/livros/$livroId'
    | '/livros/buscar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  PerfilRoute: typeof PerfilRoute
  LivrosLivroIdRoute: typeof LivrosLivroIdRoute
  LivrosBuscarRoute: typeof LivrosBuscarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livros/$livroId': {
      id: '/livros/$livroId'
      path: '/livros/$livroId'
      fullPath: '/livros/$livroId'
      preLoaderRoute: typeof LivrosLivroIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livros/buscar': {
      id: '/livros/buscar'
      path: '/livros/buscar'
      fullPath: '/livros/buscar'
      preLoaderRoute: typeof LivrosBuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  PerfilRoute: PerfilRoute,
  LivrosLivroIdRoute: LivrosLivroIdRoute,
  LivrosBuscarRoute: LivrosBuscarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
